name: OpenWrt
on:
  push:
    branches:
      - main
    paths:
      - "*.config"
  watch:
    types: started
  schedule:
    - cron: 0 12 * * */6

jobs:
  DIR819:
    runs-on: ubuntu-latest
    name: Dlink Dir 819 Rev A1
    if: github.actor == github.repository_owner
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        submodules: true

    - name: Copiler
      uses: Sirherobrine23/Actions-Build-Openwrt@main
      with:
        branch: "feature/alpha"
        url: "https://github.com/anlix-io/openwrt.git"
        config: "Dir819.config"

    - name: Upload To Releases
      uses: softprops/action-gh-release@v1
      if: env.UPLOADTORELEASE == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Build to ${{ env.DEVICE_NAME }}
        tag_name: "dir_819-${{ github.run_id }}"
        body_path: ${{ env.BODYFILE }}
        files: |
          ${{ env.RELEASEFOLDER }}/*
          !${{ env.BODYFILE }}
